language: cpp

compiler:  
    - gcc

branches:
  only:
  - master

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make && make CTEST_OUTPUT_ON_FAILURE=1 test

notifications:
  email:
    on_success: change
    on_failure: change
