language: cpp

compiler:  
  - gcc

branches:
  only:
    - master

addons:
  apt:
    packages:
      - kcov

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make CTEST_OUTPUT_ON_FAILURE=1 test

after_success:
  - mkdir coverage
  - ls -laR
  #- cd coverage
  #- gcov
  #- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: change
