language: cpp

compiler:  
  - gcc

branches:
  only:
    - master

addons:
  apt:
    packages:
      - kcov

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make CTEST_OUTPUT_ON_FAILURE=1 test

after_success:
  - ls -la
  - kcov /coverage unit_tests/unit_tests
  - bash <(curl -s https://codecov.io/bash) -s /coverage

notifications:
  email:
    on_success: change
    on_failure: change
