language: cpp

compiler:  
  - gcc

branches:
  only:
    - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make CTEST_OUTPUT_ON_FAILURE=1 test

after_success:
  - mkdir ../coverage
  - cd ../coverage
  - ls .. -laR
  - gcov ../src/*.cpp -o ../build/src/CMakeFiles/src.dir/
  - bash <(curl -s https://codecov.io/bash) -X gcov -s ./coverage

notifications:
  email:
    on_success: change
    on_failure: change
