language: cpp

compiler:  
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

branches:
  only:
  - master

script:
  - mkdir build && cd build
  - cmake .. -DENABLE_COVERAGE=On && make
  - make CTEST_OUTPUT_ON_FAILURE=1 test
  - make gcov
  - make lcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov

notifications:
  email:
    on_success: change
    on_failure: change
