language: cpp

compiler:  
    - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make  
